### ISSUE TITLE
World doesn't load.

### ISSUE THREAD

**Issue by Akitori** [jredfox/silkspawners_rewrite#1]
Hiya, world isn't loading using silk touchable spawners. It loads to the main menu, but loading a world causes it to stall.

[latest(1).log](https://github.com/jredfox/silkspawners_rewrite/files/1949458/latest.1.log)

**Comment by NullSector76** [comment]
A mod is using ASM to alter my mod contact the core mod that is doing this and report it as an issue.

**Comment by jredfox** [comment]
A mod is using ASM to alter my mod contact the core mod that is doing this and report it as an issue.
