### ISSUE TITLE
Silk Spawners causes other mods' textures to become invisible

### ISSUE THREAD

**Issue by chimericdream** [jredfox/silkspawners_rewrite#18]
**Issue:** When I try to install this mod into my pack, the textures for ender chests/tanks and for /dank/null items turn invisible. At first I thought the items somehow got deleted from my inventory, but fortunately they were still present.

**Version:** 1.8

**Steps to reproduce:**
1. Install the mods below in a minimal profile
1. Start game
1. Open inventory and search JEI for "dank" or "ender"

**ModPack/ModList:**
* forge-14.23.4.2759
* DankNull-1.12-1.4.33
* CodeChickenLib-1.12.2-3.2.1.351-universal
* EnderStorage-1.12.2-2.4.5.135-universal
* EvilNotchLib-1.2.3-SNAPSHOT-66
* jei_1.12.2-4.11.0.212
* p455w0rdslib-1.12-2.0.33
* silkspawners-1.8

**Screenshots:**
![2018-09-02_12 49 28](https://user-images.githubusercontent.com/198075/44959135-a70da800-aeaf-11e8-9555-4a7fac950b10.png)
![2018-09-02_12 49 29](https://user-images.githubusercontent.com/198075/44959136-a70da800-aeaf-11e8-881e-a57fc0e5ea1c.png)
![2018-09-02_12 49 38](https://user-images.githubusercontent.com/198075/44959137-a70da800-aeaf-11e8-8d24-e35bd2b9011b.png)
![2018-09-02_12 49 40](https://user-images.githubusercontent.com/198075/44959138-a70da800-aeaf-11e8-85ce-963f0d0d622b.png)
![2018-09-02_12 49 41](https://user-images.githubusercontent.com/198075/44959139-a70da800-aeaf-11e8-9790-29fd15d07550.png)

**Comment by jredfox** [comment]
try with just evil notch lib same error?

**Comment by jredfox** [comment]
Also try taking the item out of jei since it messes up my spawners and see if it renders

**Comment by chimericdream** [comment]
Looks like EvilNotchLib is the actual culprit. I can close this and open a new ticket there for you. The item still didn't render in my inventory, but showed up again after disabling ENL.

**Comment by jredfox** [comment]
yeah try using evil notch lib snapshot 44 and see if you still have the issue. Close this it's the wrong mod for reporting it. silkspawners is perfectly stable it's the lib that needs work

**Comment by chimericdream** [comment]
[Moved issue to the EvilNotchLib repo.](https://github.com/jredfox/evilnotchlib/issues/11)

**Comment by chimericdream** [comment]
I'll try snap 44.
