### ISSUE TITLE
Server crashing during startup

### ISSUE THREAD

**Issue by Tominator08** [jredfox/silkspawners_rewrite#60]
Version: Latest, 1.8.06
Issue: Server crashes before finishing startup.

CrashReport/Log:
[ServerCrashLog.txt](https://github.com/jredfox/silkspawners_rewrite/files/3108076/ServerCrashLog.txt)

ModPack/ModList:
![Modlist server](https://user-images.githubusercontent.com/15649890/56590128-d0b64380-65e6-11e9-9b5b-5a1c3a4ee5a2.png)

Edit: I know IItemRenderer Reborn isn't listed in the modlist, but the error still persists with it installed.

**Comment by jredfox** [comment]
silkspawners 1.8.06 requires evil notch lib snapshot 86 which has builtin iitemrenderer

**Comment by Tominator08** [comment]
Replaced all mods with latest Betas, still crashes. But with a new error log.
[latest.log](https://github.com/jredfox/silkspawners_rewrite/files/3127234/latest.log)

**Comment by jredfox** [comment]
make sure you have sponge forge installed it sounds like silkspawners is unable to run due to the asm not firing

**Comment by Tominator08** [comment]
Yes SpongeForge is installed and works with the 3 plugins that run on it
