### ISSUE TITLE
Crashing with Sponge

### ISSUE THREAD

**Issue by Tominator08** [jredfox/silkspawners_rewrite#64]
Continuation of:
https://github.com/jredfox/silkspawners_rewrite/issues/60

All mods are updated to latest beta, crashing while sponge is installed and working properly

https://github.com/jredfox/silkspawners_rewrite/files/3127234/latest.log

**Comment by jredfox** [comment]
you have other mods installed try uninstalling all of them except silkspawners and dependencies

**Comment by Tominator08** [comment]
I don't see how that would be the problem, as everything works fine without silkspawners and dependecies.
But ill try it

**Comment by jredfox** [comment]
run with just silkspawners

**Comment by jredfox** [comment]
I shouldn't have to wait a month for a response like the way you did and waited a good 30 minuets here doing nothing then fired it up myself. Yes the bug does exist I don't know why yet but, It should get fixed sometime during the cleanup on 1.8.2 release(not the pre builds)

**Comment by jredfox** [comment]
this is caused by https://github.com/jredfox/silkspawners_rewrite/issues/34
