### ISSUE TITLE
Ice and Fire Spawners "Dragon" crash the game

### ISSUE THREAD

**Issue by vraixen** [jredfox/silkspawners_rewrite#82]
Version: 1.12.2
Issue: Watching Ice and Fire dragon spanwers crash the game 
Steps to reproduce: search for "Dragon" in JEI or creative items
CrashReport/Log: users always have logs even if it doesn't crash
ModPack/ModList: https://pastebin.com/A6hyBnps

**Comment by jredfox** [comment]
the log always happens give me your log file. If one doesn't generate then copy and paste the one from your game window log.

Most likely you do not have evil notch lib and or IItemrenderer

**Comment by vraixen** [comment]
[crash-2020-01-18_16.51.31-client.txt](https://github.com/jredfox/silkspawners_rewrite/files/4083799/crash-2020-01-18_16.51.31-client.txt)

**Comment by jredfox** [comment]
that's better I will look into it later. My account security has been compromised and also I have been busy lately re-writing all my libs.

**Comment by vraixen** [comment]
i forgot to add the logs sorry.. i'll give it a try with the latest evil notch lib

**Comment by jredfox** [comment]
The crash is on their side from their code not working with minecraft default spawn system of onInitialSpawn() client side then rendering which is suppose to set initial values before rendering or default values if they don't support random spawns.

**Comment by vraixen** [comment]
there's a way to disable the entity for only ice and fire? maybe in the config file?

**Comment by jredfox** [comment]
evilnotchlib.cfg/domainEntityDeny

**Comment by vraixen** [comment]
sorry i am not confident with java and lines of code wich entities i have to add in the config file? the entities that cause the crash

**Comment by jredfox** [comment]
evil notch lib config input the mods modid found in the jar file you want then find .mcmodinfo file and it will tell you what the id of the mod you are using

**Comment by vraixen** [comment]
thank you
![image](https://user-images.githubusercontent.com/58710194/72690877-aa471980-3b20-11ea-83b8-8c3e97972656.png)

**Comment by jredfox** [comment]
@vraixen we need beta testers 2dary beta testers and coders for my projects there is new openings.
join the discord
https://discord.gg/Y8sHf52
