### ISSUE TITLE
Crash When Placing Spawner

### ISSUE THREAD

**Issue by peeburglar** [jredfox/silkspawners_rewrite#84]
Minecraft Version:1.12.2
Mod Versions: silkspawners-1.8.2-pre-release2
Issue: Game crashes when I place/break spawner
Steps to reproduce:When I place the spawner the game crashes sometimes when I break the spawner it crashes all the time
CrashReport/Log: 
[crash-2020-10-06_21.45.25-client.txt](https://github.com/jredfox/silkspawners_rewrite/files/5338384/crash-2020-10-06_21.45.25-client.txt)
[latest.log](https://github.com/jredfox/silkspawners_rewrite/files/5338394/latest.log)

**Comment by jredfox** [comment]
fixed in the beta version use the beta
